allprojects {
  apply plugin: 'eclipse'
  apply plugin: 'idea'
}

configure(subprojects) {
  apply plugin: 'java-library'
  java {
    toolchain {
      languageVersion = JavaLanguageVersion.of(25)
    }
  }

  compileJava {
    options.incremental = true
    options.encoding = 'UTF-8'
  }
}

subprojects {
  version = "$projectVersion"
  ext.appName = "$appName"
  repositories {
    mavenCentral()
    mavenLocal()
  }
}

eclipse.project.name = "$appName" + '-parent'
