# Project configuration - used for Gradle and scripts of build
appName=scene2d-ui-builder
appVersion=1.0.0
appVendor=Eliezer Dev Software Enginner
appCopyright=Copyright 2026
appDescription=Scene2d UI builder. Now you can create your huds and menus for libgdx games whithout fighting with Tables manually.
appMainClass=my_app.Main
